spring.application.name=example-02-custom-login
server.port=8082
spring.datasource.url=jdbc:h2:file:./data/example02;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.thymeleaf.cache=false
